// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        navigationVersion = '2.7.7'
        hilt_version = '2.53.1'
    }

    dependencies {
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
    }
}

plugins {
    id 'com.android.application' version '8.7.3' apply false
    id 'com.android.library' version '8.7.3' apply false
    id 'org.jetbrains.kotlin.android' version '2.0.21' apply false
    id 'org.jetbrains.kotlin.plugin.compose' version '2.0.21' apply false
    id 'com.google.devtools.ksp' version '2.0.21-1.0.28' apply false
    id 'io.gitlab.arturbosch.detekt' version '1.23.6' apply false
    id 'com.diffplug.spotless' version '6.25.0' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

task installGitHook(type: Copy) {
    description 'Installs the pre-commit git hook'
    group 'git hooks'
    from("${rootProject.projectDir}/scripts/pre-commit")
    into("${rootProject.projectDir}/.git/hooks")
    fileMode 0755
}

tasks.getByPath(':app:preBuild').dependsOn(installGitHook)
